### PR TITLE
Fail build when missing `Gemfile.lock`

### PR DESCRIPTION
**Pull request by dentarg**
https://bundler.io/v2.4/man/bundle-config.1.html

```
$ BUNDLE_FROZEN=1 bundle install
...
Bundle complete! 22 Gemfile dependencies, 40 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$ rm Gemfile.lock

$ BUNDLE_FROZEN=1 bundle install
The deployment setting requires a Gemfile.lock. Please make sure you have checked your Gemfile.lock into version control before deploying.
```

### CODE REVIEW

**Review by walro — COMMENTED** [review]
Seems reasonable, but won't work for our internal gems where we intentionally don't have a `Gemfile.lock`.

**Comment by dentarg** [comment]
> where we intentionally don't have a `Gemfile.lock`

Maybe it makes sense to override `BUNDLE_FROZEN` in those places

**Comment by jage** [comment]
Drive-by-ping to see if we want to merge or close. :)

**Comment by dentarg** [comment]
> Seems reasonable, but won't work for our internal gems where we intentionally don't have a `Gemfile.lock`.

Maybe such repos can opt-in to not have their build failed on missing lockfile?

**Comment by walro** [comment]
We could try that approach!

**Comment by jage** [comment]
> Maybe such repos can opt-in to not have their build failed on missing lockfile?

Skip if we find a `*.gemspec` file in the root? I.e. then it's a gem.

**Comment by dentarg** [comment]
> Skip if we find a `*.gemspec` file in the root? I.e. then it's a gem.

I like an opt-in (input to the action) more because it is less complexity and also quicker (no step needs to run to find out the .gemspec file exist). We do not have that many gems using this action so I feel it is fine to not be magical about it.

**Comment by dentarg** [comment]
Kinda quirky message when running without lockfile: `Removing all platforms from the bundle is not allowed` ([src](https://github.com/84codes/dev-playground84/actions/runs/7642646113/job/20822760814#step:4:35))

`BUNDLE_FROZEN` is good not only for catching missing Gemfile.lock when there should be one, it also detects the following and is more similar to how deploy behave

> Disallow changes to the Gemfile. When the Gemfile is changed and the lockfile has not been updated, running Bundler commands will be blocked. Defaults to true when --deployment is used.

I suspect the message is a bit different when the above happens.

**Review by walro — APPROVED** [review]

**Review by jage — APPROVED** [review]

**Pull request merged**
